[package]
name = "theblindhen2020"
version = "0.1.0"
authors = ["Johan Rosenkilde <jsrn@jsrn.dk>"]
edition = "2018"

[[bin]]
name = "app"
path = "app/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4.2"
ureq = { version = "*", default-features = false, features = ["json"] }
serde = { version = "1.0.114", features = ["derive"] }
