name: Rust

on:
  push:
    branches: [ master, submission ]
  pull_request:
    branches: [ master, submission ]

env:
  CARGO_TERM_COLOR: always

jobs:
  repo_action_job:
    runs-on: ubuntu-latest
    name: Run the main action in this repo
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      # The cache restore action is adapted from
      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      # but changed to have only one key. Otherwise frequent dependency changes
      # would lead to a high Actions space cost.
      - name: Restore Cargo build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-main
      - name: Build and run
        uses: ./ # Uses an action in the root directory
